---
title: Trawler Report
date: "Date: `r Sys.time()`"
output:
  html_document:
    keep_md: yes
    toc: yes
    toc_float: true
    number_sections: true
    # css: ../analysis/common/styles-1.css
params:
  path_checks: "not-set"
---

<!-- Set the report-wide options, and point to the external code file. -->
```{r set-options, echo=F}
library(knitr)

# cat("Working directory: ", getwd())
report_render_start_time <- Sys.time()
opts_chunk$set(
  results    = 'show',
  warning    = TRUE
)

echo_chunks <- FALSE
```

<!-- Suppress the output when loading packages. -->
```{r load-packages, echo = echo_chunks, message = FALSE}
requireNamespace("dplyr")
requireNamespace("DT")
```

<!-- Load any global functions and variables declared in the R file.  Suppress the output. -->
```{r declare-globals, echo = echo_chunks}
path_checks <- 
  if (params$path_checks == "not-set") {
    system.file("derived/biochemical.rds", package = "trawler")
  } else {
    params$path_checks
  }

checkmate::assert_character(path_checks, any.missing = FALSE, len = 1)
checkmate::assert_file_exists(path_checks, extension = "rds")

palette_summary <- list(warm = "#fde0ef", hot = "#f1b6da", header = "#555") #http://colrd.com/palette/18841/
```

<!-- Load the datasets.   -->
```{r load-data, echo = echo_chunks}
checks <- base::readRDS(path_checks)
```

<!-- Tweak the datasets.   -->
```{r tweak-data, echo = echo_chunks}
```


Rules {.tabset .tabset-fade}
=============================

A *rule* is very exact.  Each record is examined, and determined if it passes each specific rule.

Rule Summary
-----------------------------
```{r table-rule-summary, echo = echo_chunks}
ds_rule_summary <- checks$rules 

ds_rule_summary |>
  dplyr::mutate(
    check_name            = gsub("_", " ", check_name),
  ) |> 
  dplyr::select(
    `Rule Name`           = .data$check_name,   
    `Priority`            = .data$priority,   
    `Error Message`       = .data$error_message,   
    `Violation Count`     = .data$violation_count,  
  ) |> 
  knitr::kable(
    align     = "lrlr",
    escape    = FALSE,
    format    = "html"
  ) |>
  kableExtra::kable_styling(
    bootstrap_options = c("hover", "condensed", "responsive"), #"striped",
    full_width        = FALSE,
    position          = "left"
  ) |>
  kableExtra::row_spec(
    row         = 0,
    bold        = TRUE,
    color       = "white",
    background  = palette_summary$header
  ) |>
  kableExtra::row_spec(
    row         = seq_len(nrow(ds_rule_summary)),
    color       = "#555"
  ) |>
  kableExtra::row_spec(
    row         = which(ds_rule_summary$violation_count > 0 & ds_rule_summary$priority == 1L),
    bold        = TRUE,
    background  = palette_summary$hot
  ) |>
  kableExtra::row_spec(
    row         = which(ds_rule_summary$violation_count > 0 & ds_rule_summary$priority > 1L),
    bold        = TRUE,
    background  = palette_summary$warm
  )
```

Rule Detail
-----------------------------
```{r table-rule-detail, echo = echo_chunks}
checks$rules |>
  dplyr::select(
    .data$check_name,
    .data$error_message,
    .data$priority,
    # .data$debug,
    # .data$instrument,
    # .data$passing_test,
    .data$results
  ) |> 
  tidyr::unnest(results) |> 
  dplyr::mutate(
    # record_id         = sprintf(
    #   checks$link_specific,
    #   checks$redcap_version, checks$project_id, checks$default_arm, .data$record_id, .data$instrument, .data$record_id
    # ),
    check_name        = gsub("_", " ", .data$check_name),
  ) |> 
  dplyr::mutate(
    # DT provides a drop down filter for factors.
    check_name        = factor(.data$check_name), 
    error_message     = factor(.data$error_message), 
    data_collector    = factor(.data$data_collector),
  ) |> 
  dplyr::select(
    `Rule Name`           = .data$check_name,   
    `Priority`            = .data$priority,   
    `Error Message`       = .data$error_message,   
    `Record ID`           = .data$record_id,
    `Data Collector`      = .data$data_collector,
    `Baseline Date`       = .data$baseline_date,
  ) |> 
  {\(d)
    DT::datatable(
      data         = d,
      # colnames     = gsub("_", " ", colnames(d)),
      filter       = "top",
      caption      = paste("Violations at", Sys.time()),
      escape       = FALSE,
      options      = list(
        pageLength = 30,
        dom = "tip",
        initComplete = DT::JS(
          "function(settings, json) {",
          "$(this.api().table().header()).css({'background-color': '#555', 'color': '#fff'});",
          "}"
        )
      )
    )
  }()
```

Smells {.tabset .tabset-fade}
=============================

A *smell* test won't validate a specific record (like the rules above), but it will make sure the dataset overall smells as expected.

Smell Summary
-----------------------------
```{r table-smell-summary, echo = echo_chunks}
ds_smell_result_pretty <-
  checks$smells |>
  dplyr::transmute(
    check_name            = gsub("_", " ", check_name),
    priority,             # = wrap_violation(n, priority),
    description,
    boundaries            = sprintf(.data$bounds_template, .data$bound_lower, .data$bound_upper),
    value                 = sprintf(.data$value_template , .data$value),
    pass
    # n
  ) |>
  dplyr::arrange(priority, check_name) 

ds_smell_result_pretty |>
  dplyr::select(
    "Smell Name"           = check_name,   
    "Priority"             = priority,   
    "Proportion of..."     = description,   
    "Legal Boundaries"     = boundaries,   
    "Value"                = value,   
    "Pass"                 = pass,  
  ) |> 
  knitr::kable(
    align     = "lrllrl",
    escape    = FALSE,
    format    = "html"
  ) |>
  kableExtra::kable_styling(
    bootstrap_options = c("hover", "condensed", "responsive"), #"striped",
    full_width        = FALSE,
    position          = "left"
  ) |>
  kableExtra::row_spec(
    row         = 0,
    bold        = TRUE,
    color       = "white",
    background  = palette_summary$header
  ) |>
  kableExtra::row_spec(
    row         = seq_len(nrow(ds_smell_result_pretty)),
    color       = "#555"
  ) |>
  kableExtra::row_spec(
    row         = which(!ds_smell_result_pretty$pass & ds_smell_result_pretty$priority == 1L),
    bold        = TRUE,
    background  = palette_summary$hot
  ) |>
  kableExtra::row_spec(
    row         = which(!ds_smell_result_pretty$pass & ds_smell_result_pretty$priority >= 2L),
    bold        = TRUE,
    background  = palette_summary$warm
  )

```
